# Generated by Django 3.1.6 on 2021-02-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_pic', models.ImageField(upload_to='images/', verbose_name='choose_pic')),
            ],
        ),
        migrations.CreateModel(
            name='TakePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_pic', models.ImageField(upload_to='images/', verbose_name='take_pic')),
            ],
        ),
    ]
