# Generated by Django 3.1.6 on 2021-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/default.png', upload_to='')),
            ],
        ),
    ]
